# 1. 异常简介

* **简介**
  * 当检测到一个错误时，Python解释器就无法继续执行了，反而出现了一些错误的提示，这就是所谓的“异常”, 也就是我们常说的BUG

* **示例**

  ![image-20231128103815577](https://dawn1314.oss-cn-beijing.aliyuncs.com/typoraimg/202311281038626.png)



## 2. 异常的捕获方法

* **简介**

  * 当我们的程序遇到了BUG, 那么接下来有两种情况

    * 整个程序因为一个BUG停止运行      
    * 对BUG进行提醒, 整个程序继续运行

    我们所有的程序遇到BUG就会出现第一种的这种情况, 也就是整个程序直接奔溃.但是在真实工作中, 我们肯定不能因为一个小的BUG就让整个程序全部奔溃, 也就是我们希望的是达到第二种情况那这里我们就需要使用到捕获异常

  * 捕获异常的作用在于：提前假设某处会出现异常，做好提前准备，当真的出现异常的时候，可以有后续手段

* **捕获常规异常**

  * **基本语法**

    ```python
    try:
        可能发生错误的代码
    except:
        如果出现异常执行的代码
    ```

  * **示例**

    ```python
    try:
        # 以"r"方式打开一个不存在的文件
        with open("linux.txt", 'r') as f:
            content1 = f.read(2)
    except:
        print("常规异常捕获")
    ```

* **捕获指定异常**

  * **基本语法**

    ```python
    try:
    	print(name)
    except NameError as e:
        print("name变量名称未定义错误")
    ```

  * **总结**
    *  如果尝试执行的代码的异常类型和要捕获的异常类型不一致，则无法捕获异常
    * 一般try下方只放一行尝试执行的代码。

* **捕获多个异常**

  * **基本语法**

    ```python
    # 捕获多个异常
    try:
        print(1/0)
    except (NameError, ZeroDivisionError):
        print("ZeroDivisionError错误...")
    ```

  * **总结**

    * 当捕获多个异常时，可以把要捕获的异常类型的名字，放到except 后，并使用元组的方式进行书写

* **捕获异常并输出信息**

  ```python
  try:
  	print(name)
  except NameError as e:
      print(e)
  
  # output: name 'name' is not defined
  ```

* **捕获所有异常**

  ```python
  # 捕获所有异常
  try:
      print(name)
  except Exception as e:
      print(e)
  
  # output: name 'name' is not defined
  ```

* **异常else**

  ```python
  try:
      print(1)
  except Exception as e:
      print(e)
  else:
      print("没有异常的时候执行的代码")
  
  # output
  # 1
  # 没有异常的时候执行的代码
  ```

* **异常的finally**

  * **简介**
    * finally表示的是无论有异常都要执行的代码

  * **示例**

    ```python
    try:
        with open("test_file1.py", 'r') as f:
            f.read(4)
    except Exception as e:
        f = open("test_file.py", "r")
    else:
        print("无异常")
    finally:
        f.close()
    ```



# 3. 异常的传递

* **简介**
  * 异常是具有传递性的

* **总结**

  * 当所有的函数都没有捕获异常的时候, 程序就会报错

* **示例**

  * 当函数func01中发生异常, 并且没有捕获处理这个异常的时候, 异常会传递到函数func02, 当func02也没有捕获处理这个异常的时候main函数会捕获这个异常,  这就是异常的传递性
  * 利用异常具有传递性的特点, 当我们想要保证程序不会因为异常崩溃的时候, 就可以在main函数中设置异常捕获, 由于无论在整个程序哪里发生异常, 最终都会传递到main函数中, 这样就可以确保所有的异常都会被捕获

  <img src="https://dawn1314.oss-cn-beijing.aliyuncs.com/typoraimg/202311281109937.png" alt="image-20231128110938892" style="zoom: 67%;" />

  

# 4. Python模块

## 4.1. 模块的导入

* **简介**

  * Python 模块(Module)，是一个 Python 文件，以 .py 结尾.  模块能定义函数，类和变量，模块里也能包含可执行的代码
  *  python中有很多各种不同的模块, 每一个模块都可以帮助我们快速的实现一些功能, 比如实现和时间相关的功能就可以使用time模块我们可以认为一个模块就是一个工具包, 每一个工具包中都有各种不同的工具供我们使用进而实现各种不同的功能
  * 简单来说, 模块就是一个Python文件，里面有类、函数、变量等，我们可以拿过来用（导入模块去使用）

* **模块的导入方式**

  * **语法**

    ```python
    [from 模块名] import [模块 | 类 | 变量 | 函数 | *] [as 别名]
    ```

  * **常见组合形式**

    * import 模块名
    * from 模块名 import 类、变量、方法等
    * from 模块名 import *
    * import 模块名 as 别名
    * from 模块名 import 功能名 as 别名

  * **基本语法**

    * 语法1

      ```python
      import 模块名
      import 模块名1, 模块名2
      
      模块名.功能名()
      ```

      ```python
      import time  # 导入时间模块
      print("开始")
      time.sleep(1)  # 让程序睡眠1秒
      print("结束")
      ```

    * 语法2

      ```python
      from 模块名 import 功能名
      
      功能名()
      ```

      ```python
      from time import sleep # 导入时间模块中的sleep方法
      
      print("开始")
      sleep(1)
      print("结束")
      ```

    * 语法3

      ```python
      # 模块定义别名
      import 模块名 as 别名
      
      # 功能定义别名
      from 模块名 import 功能 as 别名
      ```

      ```python
      # 模块别名
      import time as tt
      
      tt.sleep(2)
      print("hello")
      
      # 功能别名
      from time import sleep as sl
      
      sl(2)
      print("hello")
      ```

      

## 4.2. 自定义模块

* **简介**

  * Python中已经帮我们实现了很多的模块. 不过有时候我们需要一些个性化的模块, 这里就可以通过自定义模块实现, 也就是自己制作一个模块

* **示例**

  * **新建一个test_func.py**

    ```python
    def add(x, y):
        return x + y
    if __name__ = "__main__":
        print(add(1, 1))
    
    def div(x, y):
        return x / y
    if __name__="__main__":
        print(div(1,1))
    ```

  * **导入**

    ```python
    from test_func import add
    
    print(add(1, 1))
    
    from test_func import div
    
    print(div(9, 3))
    ```

* **测试模块**

  ```python
  def add(x, y):
      return x + y
  
  
   # 测试模块
  if __name__ == "__main__": 
      print(add(1, 1))
  
  
  def div(x, y):
      return x / y
  
  
   # 测试模块
  if __name__ == "__main__":
      print(div(1, 1))
  ```

* `__all__`

  * 简介

    * 如果一个模块文件中有`__all__`变量, 当使用`from xxx import *`导入时, 只能导入这个列表中的函数

  * 示例

    * `test_func`.py

      ```python 
      __all__ = ['add']
      def add(x, y):
          return x + y
      
      
      if __name__ == "__main__":
          print(add(1, 1))
      
      
      def div(x, y):
          return x / y
      
      
      if __name__ == "__main__":
          print(div(1, 1))
      ```

    * `test_module.py`

      ```python 
      ## 第一种导入不可以调用div, 但是第二种导入方式是可以调用的
      from test_func import * # 第一种导入方式
      # from test_func import div # 第二种导入方式
      print(div(9, 3))
      ```

* **总结**

  * 当导入多个模块时, 且模块内有同名功能, 当调用这个同名功能的时候, 调用的是后面导入的模块的功能

    ```python
    # 模块1代码
    def my_test(a, b)
    	print(a + b)
    
    # 模块2代码
    def my_test(a, b)
    	print(a - b)
    
    # 导入模块和调用功能
    from my_module1 import my_test
    from my_module2 import my_test
    
    # my_test函数是模块2的函数
    my_test(1, 1)
    ```

    